/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab8_rafaeldiaz;

import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Rafael
 */
public class Lab8_RafaelDiaz extends javax.swing.JFrame {

    /**
     * Creates new form Lab8_RafaelDiaz
     */
    public Lab8_RafaelDiaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_paciente = new javax.swing.JDialog();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        fecha_ingreso = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        fecha_dealta = new com.toedter.calendar.JDateChooser();
        tf_nombre = new javax.swing.JTextField();
        tf_edad = new javax.swing.JTextField();
        tf_id = new javax.swing.JTextField();
        tf_altura = new javax.swing.JTextField();
        tf_peso = new javax.swing.JTextField();
        tf_sexo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tf_sangre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_causa = new javax.swing.JTextArea();
        jb_guardar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        tf_altura1 = new javax.swing.JTextField();
        fecha_ingreso1 = new com.toedter.calendar.JDateChooser();
        tf_peso1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        tf_sexo1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jb_mod = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        fecha_dealta1 = new com.toedter.calendar.JDateChooser();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        tf_sangre1 = new javax.swing.JTextField();
        tf_nombre1 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        tf_edad1 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        tf_id1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta_causa1 = new javax.swing.JTextArea();
        cb_modpa = new javax.swing.JComboBox<>();
        jb_alergia = new javax.swing.JButton();
        jb_enfermedad = new javax.swing.JButton();
        cb_organos = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        eliminar = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jd_doctor = new javax.swing.JDialog();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        tf_altura2 = new javax.swing.JTextField();
        tf_peso2 = new javax.swing.JTextField();
        tf_sexo2 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        tf_nombre2 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        tf_edad2 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        tf_id2 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        miercoles = new javax.swing.JCheckBox();
        martes = new javax.swing.JCheckBox();
        lunes = new javax.swing.JCheckBox();
        jueves = new javax.swing.JCheckBox();
        viernes = new javax.swing.JCheckBox();
        sabado = new javax.swing.JCheckBox();
        domingo = new javax.swing.JCheckBox();
        anios = new javax.swing.JTextField();
        horario = new javax.swing.JTextField();
        GuardarDoc = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        lunes1 = new javax.swing.JCheckBox();
        jueves1 = new javax.swing.JCheckBox();
        viernes1 = new javax.swing.JCheckBox();
        sabado1 = new javax.swing.JCheckBox();
        domingo1 = new javax.swing.JCheckBox();
        anios1 = new javax.swing.JTextField();
        horario1 = new javax.swing.JTextField();
        ModDoc1 = new javax.swing.JButton();
        tf_altura3 = new javax.swing.JTextField();
        tf_peso3 = new javax.swing.JTextField();
        tf_sexo3 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        tf_nombre3 = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        tf_edad3 = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        tf_id3 = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        miercoles1 = new javax.swing.JCheckBox();
        martes1 = new javax.swing.JCheckBox();
        jLabel43 = new javax.swing.JLabel();
        cb_moddoc = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        paci = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        eliminardoc = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jb_paciente = new javax.swing.JButton();
        jb_Doctor = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jd_paciente.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("Bienvenido!");

        jLabel3.setText("Nombre");

        jLabel4.setText("Edad");

        jLabel5.setText("ID");

        jLabel6.setText("Altura");

        jLabel7.setText("Peso");

        jLabel8.setText("Sexo");

        jLabel9.setText("Fecha de ingreso");

        jLabel10.setText("Fecha de alta");

        tf_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_idActionPerformed(evt);
            }
        });

        jLabel11.setText("Tipo de Sangre");

        jLabel12.setText("Causa de la Visita");

        ta_causa.setColumns(20);
        ta_causa.setRows(5);
        jScrollPane1.setViewportView(ta_causa);

        jb_guardar.setText("Guardar Persona");
        jb_guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_guardarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(277, 277, 277)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addGap(64, 64, 64))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addGap(47, 47, 47)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(92, 92, 92)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fecha_ingreso, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(fecha_dealta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tf_nombre)
                    .addComponent(tf_edad)
                    .addComponent(tf_id)
                    .addComponent(tf_altura)
                    .addComponent(tf_peso)
                    .addComponent(tf_sexo))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(189, 189, 189)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(tf_sangre, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE))
                            .addComponent(jScrollPane1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jb_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(87, 87, 87))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(tf_sangre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(tf_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tf_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(tf_altura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(tf_peso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8)
                                .addComponent(tf_sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(fecha_ingreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(fecha_dealta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jb_guardar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Nuevo Paciente", jPanel1);

        jLabel14.setText("Fecha de ingreso");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel15.setText("Modificar Paciente");

        jLabel16.setText("Fecha de alta");

        jb_mod.setText("Modficar Persona");
        jb_mod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_modMouseClicked(evt);
            }
        });
        jb_mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_modActionPerformed(evt);
            }
        });

        jLabel17.setText("Nombre");

        jLabel18.setText("Tipo de Sangre");

        jLabel19.setText("Edad");

        jLabel20.setText("Causa de la Visita");

        jLabel21.setText("ID");

        jLabel23.setText("Altura");

        jLabel24.setText("Peso");

        jLabel25.setText("Sexo");

        tf_id1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_id1ActionPerformed(evt);
            }
        });

        ta_causa1.setColumns(20);
        ta_causa1.setRows(5);
        jScrollPane2.setViewportView(ta_causa1);

        cb_modpa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_modpaItemStateChanged(evt);
            }
        });

        jb_alergia.setText("Agregar Alergia");
        jb_alergia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_alergiaMouseClicked(evt);
            }
        });

        jb_enfermedad.setText("Agregar enfermedad");
        jb_enfermedad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_enfermedadMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel16)
                            .addGap(64, 64, 64))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel14)
                            .addGap(47, 47, 47)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel19)
                            .addComponent(jLabel21)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25))
                        .addGap(92, 92, 92)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fecha_ingreso1, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(fecha_dealta1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tf_nombre1)
                    .addComponent(tf_edad1)
                    .addComponent(tf_id1)
                    .addComponent(tf_altura1)
                    .addComponent(tf_peso1)
                    .addComponent(tf_sexo1))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cb_organos, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel18)
                                        .addComponent(jLabel20))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tf_sangre1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jb_alergia, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(54, 54, 54)
                                    .addComponent(jb_enfermedad))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(20, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jb_mod, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(cb_modpa, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jb_mod, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cb_modpa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel17)
                                    .addComponent(tf_nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18)
                                    .addComponent(tf_sangre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(25, 25, 25)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel19)
                                            .addComponent(tf_edad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGap(30, 30, 30)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel21)
                                            .addComponent(tf_id1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(28, 28, 28)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel23)
                                            .addComponent(tf_altura1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(23, 23, 23)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel24)
                                        .addComponent(tf_peso1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jb_alergia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(278, 278, 278)
                                .addComponent(jb_enfermedad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel25)
                                .addComponent(tf_sexo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cb_organos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(fecha_ingreso1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(fecha_dealta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Modificar Paciente", jPanel2);

        jButton1.setText("Eliminar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(333, 333, 333)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(233, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(269, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Eliminar Paciente", jPanel3);

        jd_paciente.getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 830, 530));

        jLabel26.setText("Nombre");

        jLabel27.setText("Edad");

        jLabel28.setText("ID");

        jLabel29.setText("Altura");

        jLabel30.setText("Peso");

        jLabel31.setText("Sexo");

        tf_id2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_id2ActionPerformed(evt);
            }
        });

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel32.setText("Bienvenido!");

        jLabel33.setText("Años como Doctor");

        jLabel34.setText("Horario de trabajo");

        miercoles.setText("Miercoles");

        martes.setText("Martes");

        lunes.setText("Lunes");

        jueves.setText("Jueves");

        viernes.setText("Viernes");

        sabado.setText("Sabado");
        sabado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sabadoActionPerformed(evt);
            }
        });

        domingo.setText("Domingo");

        GuardarDoc.setText("Guardar");
        GuardarDoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GuardarDocMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(jLabel32))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26)
                            .addComponent(jLabel27)
                            .addComponent(jLabel28)
                            .addComponent(jLabel29)
                            .addComponent(jLabel30)
                            .addComponent(jLabel31))
                        .addGap(92, 92, 92)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_altura2)
                            .addComponent(tf_peso2)
                            .addComponent(tf_nombre2, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                            .addComponent(tf_edad2)
                            .addComponent(tf_id2)
                            .addComponent(tf_sexo2))
                        .addGap(111, 111, 111)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel33)
                            .addComponent(jLabel34)
                            .addComponent(lunes, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(martes, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(miercoles, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jueves, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(viernes, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sabado, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(domingo, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(anios)
                            .addComponent(horario, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))))
                .addContainerGap(67, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(GuardarDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel32)
                .addGap(40, 40, 40)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(tf_nombre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33)
                    .addComponent(anios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tf_edad2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel34)
                        .addComponent(horario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(tf_id2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lunes))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(tf_altura2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30)
                            .addComponent(tf_peso2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_sexo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel31)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(martes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(miercoles)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jueves)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(viernes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sabado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(domingo)))
                .addGap(26, 26, 26)
                .addComponent(GuardarDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Nuevo Doctor", jPanel5);

        lunes1.setText("Lunes");

        jueves1.setText("Jueves");

        viernes1.setText("Viernes");

        sabado1.setText("Sabado");
        sabado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sabado1ActionPerformed(evt);
            }
        });

        domingo1.setText("Domingo");

        ModDoc1.setText("Modificar");
        ModDoc1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ModDoc1MouseClicked(evt);
            }
        });

        jLabel35.setText("Nombre");

        jLabel36.setText("Edad");

        jLabel37.setText("ID");

        jLabel38.setText("Altura");

        jLabel39.setText("Peso");

        jLabel40.setText("Sexo");

        tf_id3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_id3ActionPerformed(evt);
            }
        });

        jLabel41.setText("Años como Doctor");

        jLabel42.setText("Horario de trabajo");

        miercoles1.setText("Miercoles");

        martes1.setText("Martes");

        jLabel43.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel43.setText("Modificar Doctor");

        cb_moddoc.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_moddocItemStateChanged(evt);
            }
        });

        jButton3.setText("Agregar Especialidades");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jButton4.setText("Agregar Paciente");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(paci, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(cb_moddoc, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel43)))
                .addContainerGap(188, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(68, 68, 68)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel35)
                                .addComponent(jLabel36)
                                .addComponent(jLabel37)
                                .addComponent(jLabel38)
                                .addComponent(jLabel39)
                                .addComponent(jLabel40))
                            .addGap(92, 92, 92)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tf_altura3)
                                .addComponent(tf_peso3)
                                .addComponent(tf_nombre3, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                                .addComponent(tf_edad3)
                                .addComponent(tf_id3)
                                .addComponent(tf_sexo3))
                            .addGap(111, 111, 111)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel41)
                                .addComponent(jLabel42)
                                .addComponent(lunes1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(martes1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(miercoles1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jueves1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(viernes1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(sabado1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(domingo1, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGap(31, 31, 31)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(anios1)
                                .addComponent(horario1, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                            .addGap(416, 416, 416)
                            .addComponent(ModDoc1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(40, 40, 40)))
                    .addContainerGap(69, Short.MAX_VALUE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel43)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(cb_moddoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 308, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(68, 68, 68)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel35)
                        .addComponent(tf_nombre3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel41)
                        .addComponent(anios1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(25, 25, 25)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel36)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_edad3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel42)
                            .addComponent(horario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(29, 29, 29)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel37)
                        .addComponent(tf_id3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lunes1))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addGap(28, 28, 28)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel38)
                                .addComponent(tf_altura3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(24, 24, 24)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel39)
                                .addComponent(tf_peso3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(29, 29, 29)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tf_sexo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel40)))
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(martes1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(miercoles1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jueves1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(viernes1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(sabado1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(domingo1)))
                    .addGap(26, 26, 26)
                    .addComponent(ModDoc1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(68, Short.MAX_VALUE)))
        );

        jTabbedPane2.addTab("Modificar Doctor", jPanel6);

        jButton2.setText("Eliminar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(eliminardoc, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(274, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(eliminardoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(284, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Eliminar Doctor", jPanel7);

        javax.swing.GroupLayout jd_doctorLayout = new javax.swing.GroupLayout(jd_doctor.getContentPane());
        jd_doctor.getContentPane().setLayout(jd_doctorLayout);
        jd_doctorLayout.setHorizontalGroup(
            jd_doctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_doctorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );
        jd_doctorLayout.setVerticalGroup(
            jd_doctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_doctorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jb_paciente.setText("Paciente");
        jb_paciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_pacienteMouseClicked(evt);
            }
        });
        jb_paciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_pacienteActionPerformed(evt);
            }
        });

        jb_Doctor.setText("Doctor");
        jb_Doctor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_DoctorMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Cuerpo Humano");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jb_paciente, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(jb_Doctor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jb_paciente, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jb_Doctor, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(126, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_pacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_pacienteMouseClicked
        jd_paciente.setVisible(true);
        jd_paciente.pack();
        jd_paciente.setLocationRelativeTo(this);
        jd_paciente.setModal(true);
    }//GEN-LAST:event_jb_pacienteMouseClicked

    private void jb_DoctorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_DoctorMouseClicked
        jd_doctor.setVisible(true);
        jd_doctor.pack();
        jd_doctor.setLocationRelativeTo(this);
        jd_doctor.setModal(true);
    }//GEN-LAST:event_jb_DoctorMouseClicked

    private void jb_guardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_guardarMouseClicked
        Paciente pa = new Paciente(fecha_ingreso.getDate(),fecha_dealta.getDate(), tf_sangre.getText(), ta_causa.getText(), tf_nombre.getText(), Integer.parseInt(tf_edad.getText()), tf_id.getText(), Double.parseDouble(tf_altura.getText()), Double.parseDouble(tf_peso.getText()), tf_sexo.getText());
        fecha_ingreso.setDate(new Date());
        fecha_dealta.setDate(new Date());
        tf_sangre.setText("");
        ta_causa.setText("");
        tf_nombre.setText("");
        tf_edad.setText("");
        tf_id.setText("");
        tf_altura.setText("");
        tf_peso.setText("");
        tf_sexo.setText("");
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_modpa.getModel();
        modelo.addElement(pa);
        DefaultComboBoxModel modelo1 = (DefaultComboBoxModel) eliminar.getModel();
        modelo1.addElement(pa);
        DefaultComboBoxModel modelo2 = (DefaultComboBoxModel) paci.getModel();
        modelo2.addElement(pa);
    }//GEN-LAST:event_jb_guardarMouseClicked

    private void tf_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_idActionPerformed

    private void jb_modMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_modMouseClicked
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_modpa.getModel();
        ((Paciente)modelo.getSelectedItem()).setFecha_ingreso(fecha_ingreso1.getDate());
        ((Paciente)modelo.getSelectedItem()).setFecha_dealta(fecha_dealta1.getDate());
        ((Paciente)modelo.getSelectedItem()).setTipo_sangre(tf_sangre1.getText());
        ((Paciente)modelo.getSelectedItem()).setCausa(ta_causa1.getText());
        ((Paciente)modelo.getSelectedItem()).setNombre(tf_nombre1.getText());
        ((Paciente)modelo.getSelectedItem()).setEdad(Integer.parseInt(tf_edad1.getText()));
        ((Paciente)modelo.getSelectedItem()).setId(tf_id1.getText());
        ((Paciente)modelo.getSelectedItem()).setAltura(Double.parseDouble(tf_altura1.getText()));
        ((Paciente)modelo.getSelectedItem()).setPeso(Double.parseDouble(tf_peso1.getText()));
        ((Paciente)modelo.getSelectedItem()).setSexo(tf_sexo1.getText());
        fecha_ingreso1.setDate(new Date());
        fecha_dealta1.setDate(new Date());
        tf_sangre1.setText("");
        ta_causa1.setText("");
        tf_nombre1.setText("");
        tf_edad1.setText("");
        tf_id1.setText("");
        tf_altura1.setText("");
        tf_peso1.setText("");
        tf_sexo1.setText("");
    }//GEN-LAST:event_jb_modMouseClicked

    private void tf_id1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_id1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_id1ActionPerformed

    private void jb_modActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_modActionPerformed
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_modpa.getModel();
        
        
    }//GEN-LAST:event_jb_modActionPerformed

    private void cb_modpaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_modpaItemStateChanged
       
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_modpa.getModel();
        if (cb_modpa.getSelectedIndex()>=0) {
        
        fecha_ingreso1.setDate(((Paciente)modelo.getSelectedItem()).getFecha_ingreso());
        fecha_dealta1.setDate(((Paciente)modelo.getSelectedItem()).getFecha_dealta());
        tf_sangre1.setText(((Paciente)modelo.getSelectedItem()).getTipo_sangre());
        ta_causa1.setText(((Paciente)modelo.getSelectedItem()).getCausa());
        tf_nombre1.setText(((Paciente)modelo.getSelectedItem()).getNombre());
        tf_edad1.setText(Integer.toString(((Paciente)modelo.getSelectedItem()).getEdad()));
        tf_id1.setText(((Paciente)modelo.getSelectedItem()).getId());
        tf_altura1.setText(Double.toString(((Paciente)modelo.getSelectedItem()).getAltura()));
        tf_peso1.setText(Double.toString(((Paciente)modelo.getSelectedItem()).getPeso()));
        tf_sexo1.setText(((Paciente)modelo.getSelectedItem()).getSexo());
        }
        
        
    }//GEN-LAST:event_cb_modpaItemStateChanged

    private void jb_pacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_pacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_pacienteActionPerformed

    private void jb_alergiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_alergiaMouseClicked
        String resp="s";
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_modpa.getModel();
        do{
            String alergia = JOptionPane.showInputDialog("Ingrese Alergia");
            ((Paciente)modelo.getSelectedItem()).getAlergias().add(alergia);
            resp = JOptionPane.showInputDialog("Desea agregar otra alergia? s/n");
        }while(resp.equals("s")||resp.equals("Si")||resp.equals("si")||resp.equals("S"));
    }//GEN-LAST:event_jb_alergiaMouseClicked

    private void jb_enfermedadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_enfermedadMouseClicked
        String resp="s";
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_modpa.getModel();
        do{
            String enfermedad = JOptionPane.showInputDialog("Ingrese Enfermedad");
            ((Paciente)modelo.getSelectedItem()).getAlergias().add(enfermedad);
            resp = JOptionPane.showInputDialog("Desea agregar otra enfermedad? s/n");
        }while(resp.equals("s")||resp.equals("Si")||resp.equals("si")||resp.equals("S"));
    }//GEN-LAST:event_jb_enfermedadMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) eliminar.getModel();
        DefaultComboBoxModel modelo1 = (DefaultComboBoxModel) cb_modpa.getModel();
        modelo1.removeElement(modelo.getSelectedItem());
        modelo.removeElement(modelo.getSelectedItem());
        DefaultComboBoxModel modelo2 = (DefaultComboBoxModel) paci.getModel();
        modelo2.removeElement(modelo.getSelectedItem());
    }//GEN-LAST:event_jButton1MouseClicked

    private void tf_id2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_id2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_id2ActionPerformed

    private void sabadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sabadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sabadoActionPerformed

    private void GuardarDocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GuardarDocMouseClicked
        Doctores d = new Doctores(anios.getText(), horario.getText(),tf_nombre2.getText(), Integer.parseInt(tf_edad2.getText()), tf_id2.getText(), Double.parseDouble(tf_altura2.getText()), Double.parseDouble(tf_peso2.getText()), tf_sexo2.getText() );
        if (lunes.isSelected()) {
            d.getDias_trabajo().add("Lunes");
        }
        if (martes.isSelected()) {
            d.getDias_trabajo().add("Martes");
        }
        if (miercoles.isSelected()) {
            d.getDias_trabajo().add("Miercoles");
        }
        if (jueves.isSelected()) {
            d.getDias_trabajo().add("Jueves");
        }
        if (viernes.isSelected()) {
            d.getDias_trabajo().add("Viernes");
        }
        if (sabado.isSelected()) {
            d.getDias_trabajo().add("Sabado");
        }
        if (domingo.isSelected()) {
            d.getDias_trabajo().add("Domingo");
        }
        tf_nombre2.setText("");
        tf_edad2.setText("");
        tf_id2.setText("");
        tf_altura2.setText("");
        tf_peso2.setText("");
        tf_sexo2.setText("");
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_moddoc.getModel();
        modelo.addElement(d);
        DefaultComboBoxModel modelo1 = (DefaultComboBoxModel) eliminardoc.getModel();
        modelo1.addElement(d);
    }//GEN-LAST:event_GuardarDocMouseClicked

    private void sabado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sabado1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sabado1ActionPerformed

    private void ModDoc1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModDoc1MouseClicked
        
        
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_moddoc.getModel();
        ((Doctores)modelo.getSelectedItem()).getDias_trabajo().clear();
        if (cb_moddoc.getSelectedIndex()>=0) {
        tf_nombre2.setText(((Doctores)modelo.getSelectedItem()).getNombre());
        tf_edad2.setText(Integer.toString(((Doctores)modelo.getSelectedItem()).getEdad()));
        tf_id2.setText(((Doctores)modelo.getSelectedItem()).getId());
        tf_altura2.setText(Double.toString(((Doctores)modelo.getSelectedItem()).getAltura()));
        tf_peso2.setText(Double.toString(((Doctores)modelo.getSelectedItem()).getPeso()));
        tf_sexo2.setText(((Doctores)modelo.getSelectedItem()).getSexo());
        horario1.setText(((Doctores)modelo.getSelectedItem()).getHorario());
        anios1.setText(((Doctores)modelo.getSelectedItem()).getAnios());
        if (lunes.isSelected()) {
            ((Doctores)modelo.getSelectedItem()).getDias_trabajo().add("Lunes");
        }
        if (martes.isSelected()) {
            ((Doctores)modelo.getSelectedItem()).getDias_trabajo().add("Martes");
        }
        if (miercoles.isSelected()) {
            ((Doctores)modelo.getSelectedItem()).getDias_trabajo().add("Miercoles");
        }
        if (jueves.isSelected()) {
            ((Doctores)modelo.getSelectedItem()).getDias_trabajo().add("Jueves");
        }
        if (viernes.isSelected()) {
            ((Doctores)modelo.getSelectedItem()).getDias_trabajo().add("Viernes");
        }
        if (sabado.isSelected()) {
            ((Doctores)modelo.getSelectedItem()).getDias_trabajo().add("Sabado");
        }
        if (domingo.isSelected()) {
            ((Doctores)modelo.getSelectedItem()).getDias_trabajo().add("Domingo");
        }
        }
    }//GEN-LAST:event_ModDoc1MouseClicked

    private void tf_id3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_id3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_id3ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) eliminardoc.getModel();
        DefaultComboBoxModel modelo1 = (DefaultComboBoxModel) cb_moddoc.getModel();
        modelo1.removeElement(modelo.getSelectedItem());
        modelo.removeElement(modelo.getSelectedItem());
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) paci.getModel();
        DefaultComboBoxModel modelo1 = (DefaultComboBoxModel) cb_moddoc.getModel();
        ((Doctores)modelo1.getSelectedItem()).getPacientes().add((Paciente) modelo.getSelectedItem());
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        
        String resp="s";
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_moddoc.getModel();
        do{
            String especialidad = JOptionPane.showInputDialog("Ingrese Especialidad");
            ((Doctores)modelo.getSelectedItem()).getEspecialidades().add(especialidad);
            resp = JOptionPane.showInputDialog("Desea agregar otra especialidad? s/n");
        }while(resp.equals("s")||resp.equals("Si")||resp.equals("si")||resp.equals("S"));
        
    }//GEN-LAST:event_jButton3MouseClicked

    private void cb_moddocItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_moddocItemStateChanged
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_moddoc.getModel();
        if (cb_moddoc.getSelectedIndex()>=0) {
        tf_nombre2.setText(((Paciente)modelo.getSelectedItem()).getNombre());
        tf_edad2.setText(Integer.toString(((Paciente)modelo.getSelectedItem()).getEdad()));
        tf_id2.setText(((Paciente)modelo.getSelectedItem()).getId());
        tf_altura2.setText(Double.toString(((Paciente)modelo.getSelectedItem()).getAltura()));
        tf_peso2.setText(Double.toString(((Paciente)modelo.getSelectedItem()).getPeso()));
        tf_sexo2.setText(((Paciente)modelo.getSelectedItem()).getSexo());
        horario1.setText(((Doctores)modelo.getSelectedItem()).getHorario());
        anios1.setText(((Doctores)modelo.getSelectedItem()).getAnios());
        }
        
    }//GEN-LAST:event_cb_moddocItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lab8_RafaelDiaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lab8_RafaelDiaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lab8_RafaelDiaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lab8_RafaelDiaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lab8_RafaelDiaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GuardarDoc;
    private javax.swing.JButton ModDoc1;
    private javax.swing.JTextField anios;
    private javax.swing.JTextField anios1;
    private javax.swing.JComboBox<String> cb_moddoc;
    private javax.swing.JComboBox<String> cb_modpa;
    private javax.swing.JComboBox<String> cb_organos;
    private javax.swing.JCheckBox domingo;
    private javax.swing.JCheckBox domingo1;
    private javax.swing.JComboBox<String> eliminar;
    private javax.swing.JComboBox<String> eliminardoc;
    private com.toedter.calendar.JDateChooser fecha_dealta;
    private com.toedter.calendar.JDateChooser fecha_dealta1;
    private com.toedter.calendar.JDateChooser fecha_ingreso;
    private com.toedter.calendar.JDateChooser fecha_ingreso1;
    private javax.swing.JTextField horario;
    private javax.swing.JTextField horario1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JButton jb_Doctor;
    private javax.swing.JButton jb_alergia;
    private javax.swing.JButton jb_enfermedad;
    private javax.swing.JButton jb_guardar;
    private javax.swing.JButton jb_mod;
    private javax.swing.JButton jb_paciente;
    private javax.swing.JDialog jd_doctor;
    private javax.swing.JDialog jd_paciente;
    private javax.swing.JCheckBox jueves;
    private javax.swing.JCheckBox jueves1;
    private javax.swing.JCheckBox lunes;
    private javax.swing.JCheckBox lunes1;
    private javax.swing.JCheckBox martes;
    private javax.swing.JCheckBox martes1;
    private javax.swing.JCheckBox miercoles;
    private javax.swing.JCheckBox miercoles1;
    private javax.swing.JComboBox<String> paci;
    private javax.swing.JCheckBox sabado;
    private javax.swing.JCheckBox sabado1;
    private javax.swing.JTextArea ta_causa;
    private javax.swing.JTextArea ta_causa1;
    private javax.swing.JTextField tf_altura;
    private javax.swing.JTextField tf_altura1;
    private javax.swing.JTextField tf_altura2;
    private javax.swing.JTextField tf_altura3;
    private javax.swing.JTextField tf_edad;
    private javax.swing.JTextField tf_edad1;
    private javax.swing.JTextField tf_edad2;
    private javax.swing.JTextField tf_edad3;
    private javax.swing.JTextField tf_id;
    private javax.swing.JTextField tf_id1;
    private javax.swing.JTextField tf_id2;
    private javax.swing.JTextField tf_id3;
    private javax.swing.JTextField tf_nombre;
    private javax.swing.JTextField tf_nombre1;
    private javax.swing.JTextField tf_nombre2;
    private javax.swing.JTextField tf_nombre3;
    private javax.swing.JTextField tf_peso;
    private javax.swing.JTextField tf_peso1;
    private javax.swing.JTextField tf_peso2;
    private javax.swing.JTextField tf_peso3;
    private javax.swing.JTextField tf_sangre;
    private javax.swing.JTextField tf_sangre1;
    private javax.swing.JTextField tf_sexo;
    private javax.swing.JTextField tf_sexo1;
    private javax.swing.JTextField tf_sexo2;
    private javax.swing.JTextField tf_sexo3;
    private javax.swing.JCheckBox viernes;
    private javax.swing.JCheckBox viernes1;
    // End of variables declaration//GEN-END:variables
}
